#include <stdio.h>
#include "../computer.h"

/* Even Fibonacci Numbers

   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

   1,2,3,5,8,13,21,34,55,89,…

   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

void solution1()
{
	unsigned int sum = 0;
	unsigned int a = 0;
	unsigned int b = 1;
	unsigned int c = 0;

	while (c < 4000000) {
		c = a + b;
		a = b;
		b = c;
		if (c % 2 == 0)
			sum += c;
	}

	printf("Solution 1: %d\n", sum);
}

void solution2()
{
	unsigned int sum = 0;
	unsigned int a = 1;
	unsigned int b = 1;
	unsigned int c = a + b;

	while (c < 4000000) {
		sum += c;
		a = b + c;
		b = c + a;
		c = a + b;
	}

	printf("Solution 2: %d\n", sum);
}

int main()
{
	compute(solution1());
	compute(solution2());
}
